### ISSUE TITLE
Linux and/or Windows?

### ISSUE THREAD

**Issue by WurmPeter** [Bioquilt/relixir#1]
Hello,

Nice to see somebody working on an integration of R and Elixir. 
 
Is this working only for Linux or also for Windows?  Could you give a quick example how to set up relixir? There is no package in hex, right?

Thanks.
Nef

**Comment by Bohdan-Khomtchouk** [comment]
Hi Nef,

Thanks for your note, just reading it now.  This project is currently inactive (due to my lack of bandwidth and shift in priorities) but please feel free to contribute if there's interest.  I still feel strongly about this project and believe it is needed.

Best,
Bo

**Comment by samrose** [comment]
If you are running code and consuming outputs could be worth looking at https://github.com/jayjun/rambo
